/* ==========================================================================
   NÛR — Adhkâr (rappels / formules de dhikr)
   ========================================================================== */

const ADHKAR_CATEGORIES = [
  { id: 'matin',        label: 'Matin' },
  { id: 'soir',         label: 'Soir' },
  { id: 'apres-priere', label: 'Après la prière' },
  { id: 'avant-dormir', label: 'Avant de dormir' },
];

const ADHKAR_LIST = [
  {
    id: 'ayat-kursi',
    categories: ['matin', 'soir', 'apres-priere'],
    moment: 'Après chaque prière obligatoire, et matin/soir',
    title: 'Âyat al-Kursî (le Verset du Trône)',
    ar: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۚ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۚ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۚ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    translit: "Allāhu lā ilāha illā huwa, al-ḥayyu-l-qayyūm. Lā ta'khudhuhu sinatun wa lā nawm. Lahu mā fī-s-samāwāti wa mā fī-l-arḍ. Man dhā-l-ladhī yashfa'u 'indahu illā bi'idhnih. Ya'lamu mā bayna aydīhim wa mā khalfahum. Wa lā yuḥīṭūna bishay'in min 'ilmihi illā bimā shā'. Wasi'a kursiyyuhu-s-samāwāti wa-l-arḍ. Wa lā ya'ūduhu ḥifẕuhumā. Wa huwa-l-'aliyyu-l-'aẕīm",
    fr: "Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni la somnolence ni le sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur, et ils n'embrassent de Sa science que ce qu'Il veut. Son Trône s'étend sur les cieux et la terre, et leur garde ne Lui coûte aucune peine. Et Il est le Très Haut, le Très Grand.",
    source: 'Coran 2:255',
    note: "Sa récitation après chaque prière obligatoire, ainsi que matin et soir, est l'une des formes de protection les plus importantes.",
  },
  {
    id: 'trois-sourates',
    categories: ['matin', 'soir', 'avant-dormir'],
    moment: '3 fois chacune, matin, soir et avant de dormir',
    title: 'Les trois sourates protectrices',
    fr: "Réciter trois fois chacune les sourates <b>Al-Ikhlâs</b> (112), <b>Al-Falaq</b> (113) et <b>An-Nâs</b> (114). Avant de dormir, on souffle légèrement dans ses mains jointes après les avoir récitées, puis on les passe sur le visage et tout le corps que l'on peut atteindre.",
    source: 'Rapporté par al-Bûkhârî',
    surahLinks: [112, 113, 114],
  },
  {
    id: 'matin-declaration',
    categories: ['matin'],
    moment: 'Le matin, après Fajr',
    title: 'Déclaration du matin',
    ar: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ',
    translit: "Aṣbaḥnā wa aṣbaḥa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illā-llāhu waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa huwa 'alā kulli shay'in qadīr. Rabbi as'aluka khayra mā fī hādhā-l-yawmi wa khayra mā ba'dah, wa a'ūdhu bika min sharri mā fī hādhā-l-yawmi wa sharri mā ba'dah",
    fr: "Nous voici au matin, et avec nous le règne d'Allah ; louange à Allah. Nulle divinité sinon Allah, Seul, sans associé. À Lui la royauté et la louange, et Il est capable de toute chose. Seigneur, je Te demande le bien de ce jour et le bien après lui, et je me réfugie auprès de Toi contre le mal de ce jour et le mal après lui.",
    source: 'Rapporté par Muslim',
  },
  {
    id: 'soir-declaration',
    categories: ['soir'],
    moment: 'Le soir, après Maghrib',
    title: 'Déclaration du soir',
    ar: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا',
    translit: "Amsaynā wa amsā-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illā-llāhu waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa huwa 'alā kulli shay'in qadīr. Rabbi as'aluka khayra mā fī hādhihi-l-laylati wa khayra mā ba'dahā, wa a'ūdhu bika min sharri mā fī hādhihi-l-laylati wa sharri mā ba'dahā",
    fr: "Nous voici au soir, et avec nous le règne d'Allah ; louange à Allah. Nulle divinité sinon Allah, Seul, sans associé. À Lui la royauté et la louange, et Il est capable de toute chose. Seigneur, je Te demande le bien de cette nuit et le bien après elle, et je me réfugie auprès de Toi contre le mal de cette nuit et le mal après elle.",
    source: 'Rapporté par Muslim',
  },
  {
    id: 'bika-asbahna',
    categories: ['matin'],
    moment: 'Le matin',
    title: "« Ô Allah, c'est par Toi que nous accédons au matin… »",
    ar: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَحْيَيْنَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    translit: 'Allāhumma bika aṣbaḥnā, wa bika aḥyaynā, wa bika namūtu, wa ilayka-n-nushūr',
    fr: "Ô Allah, c'est par Toi que nous accédons au matin, par Toi que nous vivons, par Toi que nous mourrons, et c'est vers Toi qu'est le retour.",
    source: 'Rapporté par at-Tirmidhî',
  },
  {
    id: 'bika-amsayna',
    categories: ['soir'],
    moment: 'Le soir',
    title: "« Ô Allah, c'est par Toi que nous accédons au soir… »",
    ar: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    translit: 'Allāhumma bika amsaynā, wa bika aṣbaḥnā, wa bika naḥyā wa bika namūtu, wa ilayka-l-maṣīr',
    fr: "Ô Allah, c'est par Toi que nous accédons au soir, par Toi que nous accédons au matin, par Toi que nous vivons et par Toi que nous mourrons, et c'est vers Toi qu'est le retour final.",
    source: 'Rapporté par at-Tirmidhî',
  },
  {
    id: 'hasbiya-allah',
    categories: ['matin', 'soir'],
    moment: 'Matin et soir (7 fois)',
    title: 'Allah me suffit (7 fois)',
    ar: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    translit: "Ḥasbiya-llāhu lā ilāha illā huwa, 'alayhi tawakkaltu wa huwa Rabbu-l-'arshi-l-'aẕīm",
    fr: "Allah me suffit, il n'y a de divinité que Lui ; je place ma confiance en Lui, et Il est le Seigneur du Trône immense.",
    source: 'Coran 9:129, formule reprise dans les invocations rapportées par Abû Dâwûd',
    note: "À répéter 7 fois le matin et 7 fois le soir.",
  },
  {
    id: 'tasbih-apres-priere',
    categories: ['apres-priere'],
    moment: 'Juste après chaque prière obligatoire',
    title: 'Tasbîh (33 + 33 + 34) après la prière',
    ar: 'سُبْحَانَ اللَّهِ (٣٣) — الْحَمْدُ لِلَّهِ (٣٣) — اللَّهُ أَكْبَرُ (٣٤)، ثُمَّ: لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    translit: "Subḥāna-llāh (×33) — Al-ḥamdu lillāh (×33) — Allāhu akbar (×34), puis : Lā ilāha illā-llāhu waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamdu wa huwa 'alā kulli shay'in qadīr",
    fr: "« Gloire à Allah » (33 fois) — « Louange à Allah » (33 fois) — « Allah est le plus Grand » (34 fois), puis : « Nulle divinité sinon Allah, Seul, sans associé. À Lui la royauté et la louange, et Il est capable de toute chose. »",
    source: 'Rapporté par Muslim',
    note: "Selon le hadith, celui qui récite cela après chaque prière obtient le pardon de ses péchés.",
  },
  {
    id: 'dua-muadh',
    categories: ['apres-priere'],
    moment: 'Après le salâm, à la fin de la prière',
    title: "Aide-moi à T'invoquer, à Te remercier et à T'adorer",
    ar: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    translit: "Allāhumma a'innī 'alā dhikrika wa shukrika wa ḥusni 'ibādatik",
    fr: "Ô Allah, aide-moi à T'invoquer, à Te remercier, et à T'adorer de la meilleure manière.",
    source: "Rapporté par Abû Dâwûd (recommandée par le Prophète ﷺ à Mu'âdh)",
  },
  {
    id: 'avant-dormir-3x',
    categories: ['avant-dormir'],
    moment: 'Avant de dormir (3 fois)',
    title: 'Protection contre le châtiment (3 fois)',
    ar: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
    translit: "Allāhumma qinī 'adhābaka yawma tab'athu 'ibādak",
    fr: "Ô Allah, protège-moi de Ton châtiment le jour où Tu ressusciteras Tes serviteurs.",
    source: 'Rapporté par Abû Dâwûd et at-Tirmidhî',
    note: "À répéter 3 fois.",
  },
];
