/* ==========================================================================
   NÛR — Bibliothèque de Du'a
   Arabe (avec voyelles) + translitération phonétique + traduction française
   + moment opportun + indication de la source.
   ========================================================================== */

const DUA_CATEGORIES = [
  { id: 'quotidien',  label: 'Vie quotidienne' },
  { id: 'famille',    label: 'Enfants & famille' },
  { id: 'parents',    label: 'Parents & défunts' },
  { id: 'mariage',    label: 'Mariage' },
  { id: 'reussite',   label: 'Réussite & travail' },
  { id: 'protection', label: 'Protection & épreuves' },
  { id: 'repentir',   label: 'Repentir & pardon' },
];

const DUA_LIST = [

  /* ---------------- Vie quotidienne ---------------- */
  {
    id: 'reveil',
    category: 'quotidien',
    moment: 'Au réveil',
    title: 'Invocation au réveil',
    ar: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    translit: "Al-ḥamdu lillāhi-l-ladhī aḥyānā ba'da mā amātanā wa ilayhi-n-nushūr",
    fr: "Louange à Allah qui nous a redonné la vie après nous avoir fait « mourir » (le sommeil), et c'est vers Lui qu'est le retour.",
    source: 'Rapporté par al-Bûkhârî',
  },
  {
    id: 'coucher',
    category: 'quotidien',
    moment: 'Avant de dormir',
    title: 'Invocation avant de dormir',
    ar: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    translit: 'Bismika Allāhumma amūtu wa aḥyā',
    fr: "C'est en Ton nom, ô Allah, que je meurs (le sommeil) et que je vis (le réveil).",
    source: 'Rapporté par al-Bûkhârî',
    note: "À compléter par la récitation des sourates <b>Al-Ikhlâs</b>, <b>Al-Falaq</b> et <b>An-Nâs</b> (chacune 3 fois), en soufflant légèrement dans les mains puis en les passant sur le visage et le corps.",
  },
  {
    id: 'sortie-maison',
    category: 'quotidien',
    moment: 'En sortant de la maison',
    title: 'Invocation en sortant de chez soi',
    ar: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    translit: "Bismillāh, tawakkaltu 'alā-llāh, wa lā ḥawla wa lā qūwwata illā billāh",
    fr: "Au nom d'Allah, je place ma confiance en Allah, il n'y a de force ni de puissance qu'en Allah.",
    source: 'Rapporté par Abû Dâwûd et at-Tirmidhî',
    note: "Selon le hadith, celui qui dit cela en sortant entend une voix lui répondre : « Tu es guidé, épargné et protégé. »",
  },
  {
    id: 'entree-maison',
    category: 'quotidien',
    moment: 'En entrant dans la maison',
    title: 'Invocation en entrant chez soi',
    ar: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
    translit: "Bismillāhi walajnā, wa bismillāhi kharajnā, wa 'alā-llāhi Rabbinā tawakkalnā",
    fr: "Au nom d'Allah nous entrons, au nom d'Allah nous sortons, et c'est en Allah, notre Seigneur, que nous plaçons notre confiance.",
    source: 'Rapporté par Abû Dâwûd',
    note: "Puis prononcer le salâm (« As-salâmu ʿalaykum »), même si la maison est vide — cela rejaillit en bien sur la personne.",
  },
  {
    id: 'avant-repas',
    category: 'quotidien',
    moment: 'Avant de manger ou boire',
    title: 'Invocation avant le repas',
    ar: 'بِسْمِ اللَّهِ',
    translit: 'Bismillāh',
    fr: "Au nom d'Allah.",
    source: 'Hadith authentique',
    note: "Si l'on a oublié de le dire au début du repas, on peut dire : « <i>Bismillāhi awwalahu wa ākhirahu</i> » (« Au nom d'Allah, au début et à la fin »).",
  },
  {
    id: 'apres-repas',
    category: 'quotidien',
    moment: 'Après avoir mangé',
    title: 'Invocation après le repas',
    ar: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا، وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    translit: "Al-ḥamdu lillāhi-l-ladhī aṭ'amanī hādhā, wa razaqanīhi min ghayri ḥawlin minnī wa lā qūwwah",
    fr: "Louange à Allah qui m'a nourri de ceci et me l'a accordé, sans aucune force ni capacité de ma part.",
    source: 'Rapporté par at-Tirmidhî',
  },
  {
    id: 'voyage',
    category: 'quotidien',
    moment: 'En montant dans un véhicule / en voyage',
    title: 'Invocation du voyage',
    ar: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    translit: "Subḥāna-l-ladhī sakhkhara lanā hādhā wa mā kunnā lahu muqrinīn, wa innā ilā Rabbinā lamunqalibūn",
    fr: "Gloire à Celui qui a mis ceci à notre service, nous n'aurions pu y parvenir par nous-mêmes. Et c'est vers notre Seigneur que nous retournerons.",
    source: 'Coran 43:13-14',
  },

  /* ---------------- Enfants & famille ---------------- */
  {
    id: 'descendance-joie',
    category: 'famille',
    moment: "Pour le bonheur et la droiture des enfants",
    title: 'Une descendance qui soit une joie pour les yeux',
    ar: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    translit: "Rabbanā hab lanā min azwājinā wa dhurriyyātinā qurrata a'yunin wa-j'alnā li-l-muttaqīna imāmā",
    fr: "Notre Seigneur, fais que nos épouses et nos descendants soient pour nous une source de joie, et fais de nous un modèle pour les pieux.",
    source: 'Coran 25:74',
    note: "Une invocation idéale à répéter régulièrement pour que tes enfants grandissent heureux et deviennent de bonnes personnes.",
  },
  {
    id: 'enfants-priere',
    category: 'famille',
    moment: 'Pour la pratique religieuse des enfants',
    title: 'Que mes enfants restent attachés à la prière',
    ar: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِنْ ذُرِّيَّتِي، رَبَّنَا وَتَقَبَّلْ دُعَاءِ',
    translit: "Rabbi-j'alnī muqīma-ṣ-ṣalāti wa min dhurriyyatī, Rabbanā wa taqabbal du'ā'",
    fr: "Mon Seigneur, fais que j'accomplisse assidûment la prière, et fais qu'il en soit de même pour ma descendance. Ô notre Seigneur, accepte mon invocation.",
    source: "Coran 14:40 (invocation du prophète Ibrâhîm ﷺ)",
  },
  {
    id: 'protection-enfants',
    category: 'famille',
    moment: 'Pour protéger ses enfants (le soir, en cas d\'inquiétude)',
    title: 'Confier ses enfants à la protection d\'Allah',
    ar: 'أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ، مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
    translit: "U'īdhukumā bikalimāti-llāhi-t-tāmmati, min kulli shayṭānin wa hāmmah, wa min kulli 'aynin lāmmah",
    fr: "Je vous place tous les deux sous la protection des paroles parfaites d'Allah, contre tout démon, toute créature nuisible, et tout regard mauvais.",
    source: 'Rapporté par al-Bûkhârî',
    note: "Le Prophète ﷺ récitait cette invocation pour protéger ses petits-fils Hassan et Hussein. Au singulier pour un seul enfant : remplacer « <i>ukumā</i> » par « <i>uka</i> » (pour un garçon) ou « <i>uki</i> » (pour une fille).",
  },

  /* ---------------- Parents & défunts ---------------- */
  {
    id: 'misericorde-parents',
    category: 'parents',
    moment: 'Pour ses parents (vivants ou décédés)',
    title: 'Miséricorde pour les parents',
    ar: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translit: 'Rabbi-rḥamhumā kamā rabbayānī ṣaghīrā',
    fr: "Seigneur, fais-leur miséricorde comme ils m'ont élevé tout petit.",
    source: 'Coran 17:24',
    note: "Une des invocations les plus belles à dédier à tes deux parents.",
  },
  {
    id: 'pardon-parents-defunts',
    category: 'parents',
    moment: 'Pour le pardon de parents décédés',
    title: 'Pardon et miséricorde pour ses parents disparus',
    ar: 'اللَّهُمَّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translit: "Allāhumma-ghfir lī wa liwālidayya wa-rḥamhumā kamā rabbayānī ṣaghīrā",
    fr: "Ô Allah, pardonne-moi ainsi qu'à mes parents, et fais-leur miséricorde comme ils m'ont élevé tout petit.",
    source: "Formule combinant le pardon et l'invocation de Coran 17:24",
  },
  {
    id: 'pardon-defunt',
    category: 'parents',
    moment: 'Pour un défunt (parent, frère, proche)',
    title: 'Pardon, miséricorde et délivrance pour un défunt',
    ar: 'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ',
    translit: "Allāhumma-ghfir lahu wa-rḥamhu wa 'āfihi wa-'fu 'anhu",
    fr: "Ô Allah, pardonne-lui, fais-lui miséricorde, accorde-lui la guérison (l'apaisement) et efface ses fautes.",
    source: 'Extrait de l\'invocation funéraire, rapporté par Muslim',
    note: "Au féminin, remplacer « <i>lahu</i> » (lui, masc.) par « <i>lahā</i> » (elle) : « <i>Allāhumma-ghfir lahā wa-rḥamhā wa 'āfihā wa-'fu 'anhā</i> ». Tu peux réciter cette invocation pour ton père, ta mère ou ton frère.",
  },
  {
    id: 'elever-degre-defunt',
    category: 'parents',
    moment: 'Pour élever le défunt en degré au Paradis',
    title: 'Élargir et illuminer la tombe du défunt',
    ar: 'اللَّهُمَّ افْسَحْ لَهُ فِي قَبْرِهِ وَنَوِّرْ لَهُ فِيهِ',
    translit: "Allāhumma-fsaḥ lahu fī qabrihi wa nawwir lahu fīh",
    fr: "Ô Allah, élargis sa tombe et illumine-la pour lui.",
    source: 'Extrait de l\'invocation funéraire, rapporté par Muslim',
    note: "Au féminin : « <i>Allāhumma-fsaḥ lahā fī qabrihā wa nawwir lahā fīh</i> ».",
  },

  /* ---------------- Mariage ---------------- */
  {
    id: 'istikhara',
    category: 'mariage',
    moment: "Pour demander conseil à Allah (décision importante : mariage, projet…)",
    title: "Invocation de l'Istikhâra",
    ar: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ، وَتَعْلَمُ وَلَا أَعْلَمُ، وَأَنْتَ عَلَّامُ الْغُيُوبِ، اللَّهُمَّ إِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ خَيْرٌ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاقْدُرْهُ لِي وَيَسِّرْهُ لِي ثُمَّ بَارِكْ لِي فِيهِ، وَإِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ شَرٌّ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاصْرِفْهُ عَنِّي وَاصْرِفْنِي عَنْهُ، وَاقْدُرْ لِي الْخَيْرَ حَيْثُ كَانَ ثُمَّ أَرْضِنِي بِهِ',
    translit: "Allāhumma innī astakhīruka bi'ilmika, wa astaqdiruka biqudratika, wa as'aluka min faḍlika-l-'aẕīm. Fa innaka taqdiru wa lā aqdir, wa ta'lamu wa lā a'lam, wa anta 'allāmu-l-ghuyūb. Allāhumma in kunta ta'lamu anna hādhā-l-amra khayrun lī fī dīnī wa ma'āshī wa 'āqibati amrī, faqdurhu lī wa yassirhu lī thumma bārik lī fīh. Wa in kunta ta'lamu anna hādhā-l-amra sharrun lī fī dīnī wa ma'āshī wa 'āqibati amrī, faṣrifhu 'annī wa-ṣrifnī 'anhu, wa-qdur lī-l-khayra ḥaythu kāna thumma arḍinī bih",
    fr: "Ô Allah, je Te demande de me guider par Ta science, et je Te demande de m'accorder les moyens par Ta puissance, et je sollicite de Ton immense faveur. Car Tu es capable et je ne le suis pas, Tu sais et je ne sais pas, et Tu es Celui qui connaît parfaitement les choses cachées. Ô Allah, si Tu sais que cette affaire est un bien pour moi dans ma religion, ma vie et l'issue de mes affaires, alors facilite-la-moi et bénis-la-moi. Et si Tu sais que cette affaire est un mal pour moi dans ma religion, ma vie et l'issue de mes affaires, alors écarte-la de moi et écarte-moi d'elle, et accorde-moi le bien où qu'il se trouve, puis rends-moi satisfait de cela.",
    source: 'Rapporté par al-Bûkhârî',
    note: "À réciter après avoir accompli 2 unités de prière surérogatoire (Salât al-Istikhâra), en ayant à l'esprit la décision concernée (par exemple un projet de mariage) au moment de dire « cette affaire ».",
  },
  {
    id: 'bonne-epouse',
    category: 'mariage',
    moment: 'Pour le bien dans son futur conjoint',
    title: 'Demander le bien dans son épouse / époux',
    ar: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ خَيْرِهَا وَخَيْرِ مَا جَبَلْتَهَا عَلَيْهِ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا جَبَلْتَهَا عَلَيْهِ',
    translit: "Allāhumma innī as'aluka min khayrihā wa khayri mā jabaltahā 'alayh, wa a'ūdhu bika min sharrihā wa sharri mā jabaltahā 'alayh",
    fr: "Ô Allah, je Te demande le bien qui est en elle et le bien sur lequel Tu l'as façonnée, et je me réfugie auprès de Toi contre le mal qui est en elle et le mal sur lequel Tu l'as façonnée.",
    source: 'Rapporté par Abû Dâwûd',
    note: "Au masculin (pour une femme qui invoque au sujet d'un homme) : remplacer « <i>hā</i> » par « <i>hu</i> » → « <i>khayrihi… jabaltahu… sharrihi… jabaltahu</i> ».",
  },

  /* ---------------- Réussite & travail ---------------- */
  {
    id: 'facilite',
    category: 'reussite',
    moment: 'Avant une tâche difficile, un entretien, un nouveau projet',
    title: "Invocation pour la facilité",
    ar: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',
    translit: 'Rabbi-shraḥ lī ṣadrī, wa yassir lī amrī',
    fr: "Seigneur, ouvre-moi ma poitrine (donne-moi la sérénité) et facilite-moi ma tâche.",
    source: "Coran 20:25-26 (invocation du prophète Moïse ﷺ)",
  },
  {
    id: 'subsistance-licite',
    category: 'reussite',
    moment: 'Pour une activité professionnelle / un revenu licite',
    title: "Suffisance par le licite",
    ar: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    translit: "Allāhumma-kfinī biḥalālika 'an ḥarāmika, wa aghninī bifaḍlika 'amman siwāk",
    fr: "Ô Allah, suffis-moi par ce qui est licite, à l'écart de ce qui est illicite, et enrichis-moi par Ta grâce, me dispensant de recourir à quiconque d'autre que Toi.",
    source: 'Rapporté par at-Tirmidhî',
    note: "Particulièrement adaptée pour quelqu'un qui se lance dans une nouvelle activité (par exemple en tant qu'indépendant).",
  },
  {
    id: 'gratitude-action',
    category: 'reussite',
    moment: 'Pour rester reconnaissant dans la réussite',
    title: "Gratitude et bonnes œuvres",
    ar: 'رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ، وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ',
    translit: "Rabbi awzi'nī an ashkura ni'mataka-l-latī an'amta 'alayya wa 'alā wālidayya, wa an a'mala ṣāliḥan tarḍāh",
    fr: "Seigneur, fais que je Te sois reconnaissant pour Ton bienfait dont Tu m'as comblé, ainsi que mes parents, et fais que j'accomplisse de bonnes œuvres que Tu agrées.",
    source: 'Coran 27:19',
  },

  /* ---------------- Protection & épreuves ---------------- */
  {
    id: 'hasbunallah',
    category: 'protection',
    moment: 'Face à une difficulté ou une injustice',
    title: 'Allah nous suffit',
    ar: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    translit: "Ḥasbunā-llāhu wa ni'ma-l-wakīl",
    fr: "Allah nous suffit, et Il est le meilleur garant.",
    source: 'Coran 3:173',
  },
  {
    id: 'dua-younous',
    category: 'protection',
    moment: "Face à l'angoisse ou la détresse",
    title: "Invocation du prophète Yûnus (Jonas)",
    ar: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    translit: "Lā ilāha illā anta subḥānaka innī kuntu mina-ẕ-ẕālimīn",
    fr: "Il n'y a de divinité que Toi, gloire et pureté à Toi. J'ai vraiment été injuste envers moi-même.",
    source: 'Coran 21:87',
    note: "Allah a répondu à cette invocation et a délivré le prophète Yûnus de sa détresse.",
  },
  {
    id: 'souci-tristesse',
    category: 'protection',
    moment: 'Contre le souci, la tristesse et les soucis financiers',
    title: 'Protection contre le souci et la tristesse',
    ar: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    translit: "Allāhumma innī a'ūdhu bika mina-l-hammi wa-l-ḥazan, wa-l-'ajzi wa-l-kasal, wa-l-bukhli wa-l-jubn, wa ḍala'i-d-dayni wa ghalabati-r-rijāl",
    fr: "Ô Allah, je me réfugie auprès de Toi contre le souci et la tristesse, l'incapacité et la paresse, l'avarice et la lâcheté, le poids des dettes et la domination injuste des hommes.",
    source: 'Rapporté par al-Bûkhârî',
  },

  /* ---------------- Repentir & pardon ---------------- */
  {
    id: 'sayyid-istighfar',
    category: 'repentir',
    moment: 'Matin et soir — le meilleur istighfar',
    title: "Le maître des invocations de pardon (Sayyid al-Istighfâr)",
    ar: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    translit: "Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana 'abduk, wa ana 'alā 'ahdika wa wa'dika ma-staṭa't. A'ūdhu bika min sharri mā ṣana't, abū'u laka bini'matika 'alayya, wa abū'u bidhanbī faghfir lī, fa innahu lā yaghfiru-dh-dhunūba illā ant",
    fr: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. Tu m'as créé et je suis Ton serviteur ; je m'efforce de tenir mon engagement et ma promesse envers Toi, autant que je le peux. Je me réfugie auprès de Toi contre le mal que j'ai commis. Je reconnais envers Toi Ton bienfait sur moi, et je reconnais mon péché : pardonne-moi donc, car nul ne pardonne les péchés sinon Toi.",
    source: 'Rapporté par al-Bûkhârî',
    note: "Selon le hadith, celui qui le récite avec certitude le matin ou le soir et meurt dans la journée ou la nuit qui suit entre au Paradis.",
  },
  {
    id: 'istighfar-simple',
    category: 'repentir',
    moment: 'À répéter régulièrement',
    title: 'Demande de pardon et de repentir',
    ar: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ، إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ',
    translit: "Rabbi-ghfir lī wa tub 'alayya, innaka anta-t-tawwābu-r-raḥīm",
    fr: "Seigneur, pardonne-moi et accepte mon repentir, Tu es Celui qui accueille le repentir, le Très Miséricordieux.",
    source: "Formule s'inspirant du vocabulaire coranique (cf. Coran 49:12)",
  },
];
